// <auto-generated />
using System;
using GozbichkaWebApp.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GozbichkaWebApp.Migrations
{
    [DbContext(typeof(RecipeDBContext))]
    partial class RecipeDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GozbichkaWebApp.Models.Allergen", b =>
                {
                    b.Property<int>("AllergenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AllergenId"));

                    b.Property<string>("AllergenName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AllergenId");

                    b.ToTable("Allergens");
                });

            modelBuilder.Entity("GozbichkaWebApp.Models.Difficulty", b =>
                {
                    b.Property<int>("DifficultyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DifficultyId"));

                    b.Property<int>("DifficultyType")
                        .HasColumnType("int");

                    b.HasKey("DifficultyId");

                    b.ToTable("Difficulties");
                });

            modelBuilder.Entity("GozbichkaWebApp.Models.Favorites", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RecipeId");

                    b.HasIndex("RecipeId");

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("GozbichkaWebApp.Models.History", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ViewAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId", "RecipeId", "ViewAt");

                    b.HasIndex("RecipeId");

                    b.ToTable("Histories");
                });

            modelBuilder.Entity("GozbichkaWebApp.Models.MealCategory", b =>
                {
                    b.Property<int>("MealCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MealCategoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MealCategoryId");

                    b.ToTable("MealCategories");
                });

            modelBuilder.Entity("GozbichkaWebApp.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("GozbichkaWebApp.Models.ProductAllergen", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("AllergenId")
                        .HasColumnType("int");

                    b.HasKey("ProductId", "AllergenId");

                    b.HasIndex("AllergenId");

                    b.ToTable("ProductAllergens");
                });

            modelBuilder.Entity("GozbichkaWebApp.Models.Rating", b =>
                {
                    b.Property<int>("RatingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RatingId"));

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("RatingId");

                    b.HasIndex("RecipeId");

                    b.HasIndex("UserId");

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("GozbichkaWebApp.Models.Recipe", b =>
                {
                    b.Property<int>("RecipeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecipeId"));

                    b.Property<double>("CookingTime")
                        .HasColumnType("float");

                    b.Property<int>("DifficultyId")
                        .HasColumnType("int");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MealCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("Portions")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RecipeId");

                    b.HasIndex("DifficultyId");

                    b.HasIndex("MealCategoryId");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("GozbichkaWebApp.Models.RecipeProduct", b =>
                {
                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<double>("Quantity")
                        .HasColumnType("float");

                    b.Property<int?>("SubstituteProductId")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isOptional")
                        .HasColumnType("bit");

                    b.HasKey("RecipeId", "ProductId");

                    b.HasIndex("ProductId");

                    b.HasIndex("SubstituteProductId");

                    b.ToTable("RecipeProducts");
                });

            modelBuilder.Entity("GozbichkaWebApp.Models.RecipeSeasonalCategory", b =>
                {
                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.Property<int>("SeasonalCategoryId")
                        .HasColumnType("int");

                    b.HasKey("RecipeId", "SeasonalCategoryId");

                    b.HasIndex("SeasonalCategoryId");

                    b.ToTable("RecipeSeasonalCategories");
                });

            modelBuilder.Entity("GozbichkaWebApp.Models.RecipeStep", b =>
                {
                    b.Property<int>("RecipeStepId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecipeStepId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.Property<int>("StepNumber")
                        .HasColumnType("int");

                    b.HasKey("RecipeStepId");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeSteps");
                });

            modelBuilder.Entity("GozbichkaWebApp.Models.Refrigerator", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("bit");

                    b.HasKey("UserId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("Refrigerators");
                });

            modelBuilder.Entity("GozbichkaWebApp.Models.SeasonalCategory", b =>
                {
                    b.Property<int>("SeasonalCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SeasonalCategoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SeasonalCategoryId");

                    b.ToTable("SeasonalCategories");
                });

            modelBuilder.Entity("GozbichkaWebApp.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IconURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GozbichkaWebApp.Models.UserAllergen", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("AllergenId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "AllergenId");

                    b.HasIndex("AllergenId");

                    b.ToTable("UserAllergens");
                });

            modelBuilder.Entity("GozbichkaWebApp.Models.Favorites", b =>
                {
                    b.HasOne("GozbichkaWebApp.Models.Recipe", "Recipe")
                        .WithMany("FavoriteRecipes")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GozbichkaWebApp.Models.User", "User")
                        .WithMany("Favorites")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GozbichkaWebApp.Models.History", b =>
                {
                    b.HasOne("GozbichkaWebApp.Models.Recipe", "Recipe")
                        .WithMany("HistoryRecipes")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GozbichkaWebApp.Models.User", "User")
                        .WithMany("Histories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GozbichkaWebApp.Models.ProductAllergen", b =>
                {
                    b.HasOne("GozbichkaWebApp.Models.Allergen", "Allergen")
                        .WithMany("ProductAllergens")
                        .HasForeignKey("AllergenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GozbichkaWebApp.Models.Product", "Product")
                        .WithMany("ProductAllergens")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Allergen");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("GozbichkaWebApp.Models.Rating", b =>
                {
                    b.HasOne("GozbichkaWebApp.Models.Recipe", "Recipe")
                        .WithMany("Ratings")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GozbichkaWebApp.Models.User", "User")
                        .WithMany("Ratings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GozbichkaWebApp.Models.Recipe", b =>
                {
                    b.HasOne("GozbichkaWebApp.Models.Difficulty", "Difficulty")
                        .WithMany("Recipes")
                        .HasForeignKey("DifficultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GozbichkaWebApp.Models.MealCategory", "MealCategory")
                        .WithMany("Recipes")
                        .HasForeignKey("MealCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Difficulty");

                    b.Navigation("MealCategory");
                });

            modelBuilder.Entity("GozbichkaWebApp.Models.RecipeProduct", b =>
                {
                    b.HasOne("GozbichkaWebApp.Models.Product", "Product")
                        .WithMany("RecipeProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GozbichkaWebApp.Models.Recipe", "Recipe")
                        .WithMany("RecipeProducts")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GozbichkaWebApp.Models.Product", "SubstituteProduct")
                        .WithMany()
                        .HasForeignKey("SubstituteProductId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Product");

                    b.Navigation("Recipe");

                    b.Navigation("SubstituteProduct");
                });

            modelBuilder.Entity("GozbichkaWebApp.Models.RecipeSeasonalCategory", b =>
                {
                    b.HasOne("GozbichkaWebApp.Models.Recipe", "Recipe")
                        .WithMany("RecipeSeasonalCategories")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GozbichkaWebApp.Models.SeasonalCategory", "SeasonalCategory")
                        .WithMany("RecipeSeasonalCategories")
                        .HasForeignKey("SeasonalCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");

                    b.Navigation("SeasonalCategory");
                });

            modelBuilder.Entity("GozbichkaWebApp.Models.RecipeStep", b =>
                {
                    b.HasOne("GozbichkaWebApp.Models.Recipe", "Recipe")
                        .WithMany("RecipeSteps")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("GozbichkaWebApp.Models.Refrigerator", b =>
                {
                    b.HasOne("GozbichkaWebApp.Models.Product", "Product")
                        .WithMany("Refrigerators")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GozbichkaWebApp.Models.User", "User")
                        .WithMany("Refrigerators")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GozbichkaWebApp.Models.UserAllergen", b =>
                {
                    b.HasOne("GozbichkaWebApp.Models.Allergen", "Allergens")
                        .WithMany("UserAllergens")
                        .HasForeignKey("AllergenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GozbichkaWebApp.Models.User", "User")
                        .WithMany("UserAllergens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Allergens");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GozbichkaWebApp.Models.Allergen", b =>
                {
                    b.Navigation("ProductAllergens");

                    b.Navigation("UserAllergens");
                });

            modelBuilder.Entity("GozbichkaWebApp.Models.Difficulty", b =>
                {
                    b.Navigation("Recipes");
                });

            modelBuilder.Entity("GozbichkaWebApp.Models.MealCategory", b =>
                {
                    b.Navigation("Recipes");
                });

            modelBuilder.Entity("GozbichkaWebApp.Models.Product", b =>
                {
                    b.Navigation("ProductAllergens");

                    b.Navigation("RecipeProducts");

                    b.Navigation("Refrigerators");
                });

            modelBuilder.Entity("GozbichkaWebApp.Models.Recipe", b =>
                {
                    b.Navigation("FavoriteRecipes");

                    b.Navigation("HistoryRecipes");

                    b.Navigation("Ratings");

                    b.Navigation("RecipeProducts");

                    b.Navigation("RecipeSeasonalCategories");

                    b.Navigation("RecipeSteps");
                });

            modelBuilder.Entity("GozbichkaWebApp.Models.SeasonalCategory", b =>
                {
                    b.Navigation("RecipeSeasonalCategories");
                });

            modelBuilder.Entity("GozbichkaWebApp.Models.User", b =>
                {
                    b.Navigation("Favorites");

                    b.Navigation("Histories");

                    b.Navigation("Ratings");

                    b.Navigation("Refrigerators");

                    b.Navigation("UserAllergens");
                });
#pragma warning restore 612, 618
        }
    }
}
